# Generated by Django 4.2.4 on 2024-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webinars'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
